package online.mmdwz.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2017-6-27 0:10:16 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mmdwz")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2519012694590385914L;
	private int id;
	private String name;
	private String password;
	private int gender;

	public User() {
	}

	public User(String name, String password, int gender) {
		this.name = name;
		this.password = password;
		this.gender = gender;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "gender", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

}
